config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :us, controllers: {
    omniauth_callbacks: 'us/omniauth_callbacks',
    #sessions: 'us/sessions',
    #registrations: 'us/registrations'
  }
	root "articles#index"

  resources :articles do
    resources :comments
  end

	#get '/signup' => 'users#new'
  #post '/users' => 'users#create'

  #get '/signin' => 'sessions#new'
 # post '/signin' => 'sessions#create'
  #get '/signout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	include Visible
	#has_one :u dependent: :destroy
	belongs_to :article
	#belongs_to :u
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :load_article

	def create
		begin
			#comment_params.merge!(:article_id => @article.id)
			@comment = @article.comments.create(comment_params)
		rescue StandardError => e
			logger.error "letter_controller::create => exception #{e.class.name} : #{e.message}"
			flash[:alert] = "Detailed error: #{e.message}"
			render :new, status: :unprocessable_entity
		end
		redirect_to article_path(@article)
	end

	def destroy
		@comment = @article.comments.find_by(params[:id])
		if @comment
			@comment.destroy
		else
			flash[:alert] = "No such comment found"
			return
		end
		redirect_to article_path(@article), status: 303
	end

	private
	def comment_params
		params.require(:comment).permit(:commenter, :body, :status)
	end

	def load_article
		@article = Article.find_by(id: params[:article_id])
		if @article.nil?
			flash[:alert] = "No such article found"
			redirect_to root_path
			return
		end
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% if !comment.archived? %>
	<div class="div_text">
		<div
			<strong> <h4>Commenter:</h4></strong>
			<%= comment.commenter %>
		</div>

		<div>
			<strong> <h4>Comment:</h4></strong>
			<%= comment.body %>
		</div>

			<div>
				<%= link_to "Destroy Comment", [comment.article, comment], data: {
					method: :delete,
					confirm: "Are you sure?"
				} %>
			</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
	<div class="form-style-9">
		<%= form.label :commenter %><br>
		<%= form.text_field :commenter, :disabled => false, :readonly=> true,  value: current_u.email %>
	</div>
	<div class="form-style-9">
		<%= form.label :body %><br>
		<%= form.text_area :body %>
	</div>

	<div class="form-style-9">
		<%= form.label :status %><br>
		<%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
	</div>

	<div class="form-style-9">
		<%= form.submit %>
	</div>
<% end %>