config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :us, controllers: {
    omniauth_callbacks: 'us/omniauth_callbacks',
    #sessions: 'us/sessions',
    #registrations: 'us/registrations'
  }
	root "articles#index"

  resources :articles do
    resources :comments
  end

	#get '/signup' => 'users#new'
  #post '/users' => 'users#create'

  #get '/signin' => 'sessions#new'
 # post '/signin' => 'sessions#create'
  #get '/signout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
	include Visible
  has_many :comments, dependent: :destroy
	belongs_to :u
  validates :title, presence: true, :uniqueness => true
  validates :body, presence: true, length: { minimum: 10 }

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :load_user, only: [:create, :update, :destroy, :validate_permission_to_edit_or_delete]
	before_action :load_article, except: [:index, :new, :create]
	before_action :validate_permission_to_edit_or_delete, only: [:update, :destroy]

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		begin
			#@params = article_params
			#@params.merge!(:u_id => current_u.id)
			@article = current_u.articles.create(article_params)
			@article.save!
			redirect_to @article
		rescue => e
			flash[:alert] = "Detailed error: #{e.message}"
			redirect_to root_path
		end
	end

	def update
		if @article.update!(article_params)
			redirect_to @article
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@article.destroy!
		redirect_to root_path, status: :see_other
	end

	private
	def article_params
		params.require(:article).permit(:title, :body, :status)
	end

	def load_article
		@article = Article.find_by(id: params[:id])
		if @article.nil?
			flash[:alert] = "No such article found"
			redirect_to root_path
			return
		end
	end

	def validate_permission_to_edit_or_delete
		@current_user_article = current_u.articles.find_by(id: params[:id])
		if @current_user_article.nil? && !current_u.admin
			flash[:alert] = "You are not authorized to edit or delete this article"
			redirect_to article_path(@article)
			return
		end
	end

	def load_user
		if !current_u
			flash[:alert] = " Please Sign in to continue "
			redirect_to root_path
			return
		end
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
	<div class="form-style-9">
		<%= form.label :title %><br>
		<%= form.text_field :title %>
		<% article.errors.full_messages_for(:title).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-style-9">
		<%= form.label :body %><br>
		<%= form.text_area :body %><br>
		<% article.errors.full_messages_for(:body).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>

	<div class="form-style-9">
		<%= form.label :status %><br>
		<%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
	</div>

	<div class="form-style-9">
		<%= form.submit %>
	</div>
	<% flash.each do |type, msg| %>
		<div class="alert" >
			<%= msg %>
		</div>
	<% end %>
<% end %>

app/views/articles/edit.html.erb
<div class="form-style-9">
   <h1>Edit Article</h1>
   <%= render "form", article: @article %>
</div>

app/views/articles/index.html.erb
<body>
	<% if  u_signed_in? %>
		<%= link_to "Hi, #{current_u.email}", edit_u_registration_path %> | <%= link_to 'Sign Out', destroy_u_session_path, method: :delete %>
	<% else %>
		<h2>You're Logged out!</h2>
		<%= link_to "Sign up", new_u_registration_path %> | <%= link_to "Sign in",  new_u_session_path %>
		<%= link_to "Sign in with Google", u_google_oauth2_omniauth_authorize_path , method: :post %>
		 <%= link_to "Sign in to active admin", new_admin_user_session_path %>
	<% end %>

	<%= yield %>
</body>
<div class="form-style-9">
	<h1 >Articles</h1>

	<h3 class="head_text">Our blog has <%= Article.public_count %> articles and counting!</h3>
	<ul>
		<% @articles.each do |article| %>
			<% unless article.archived? %>
				<li>
					<%= link_to article.title, article %>
				</li>
			<% end %>
		<% end %>
	</ul>
	<button class="button-27" role="button"><%= link_to "New Article", new_article_path %> </button>
	<% flash.each do |type, msg| %>
		<div class ="alert">
			<%= msg %>
		</div>
	<% end %>
</div>

app/views/articles/new.html.erb
<div class="form-style-9">
		<h1>New Article</h1>
		<%= render "form", article: @article %>
		<% flash.each do |type, msg| %>
			<div>
				<%= msg %>
			</div>
		<% end %>
</div>

app/views/articles/show.html.erb
<div class="article form-style-9">
	<h1><%= @article.title %></h1>
	<div class="art_text"><%= @article.body %></div>
</div>

<div class="option form-style-9">
	<ul>
		<li><%= link_to "Edit", edit_article_path(@article) %></li>
		<li><%= link_to "Destroy", article_path(@article),data: {
			method: :delete} %></li>
	</ul>
</div>
<% flash.each do |type, msg| %>
	<div class = "alert" >
		<%= msg %>
	</div>
<% end %>
<div class="form-style-9">
	<h2>Comments</h2>
	<%= render @article.comments %>
	<% if current_u %>
		<h2>Add a comment:</h2>
		<%= render 'comments/form' %>
	<% end %>
</div>